# Generated by Django 3.2.2 on 2021-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('prductRating', models.CharField(max_length=10, null=True)),
                ('priceRating', models.CharField(max_length=10, null=True)),
                ('purchaseRating', models.CharField(max_length=10, null=True)),
                ('recommendRating', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
